Shift stack support
rh-nfv-int/testpmd-operator pull request #6
Opened 2021-05-20 06:41 UTC by krsacme

2021-05-20 06:43 UTC, krsacme commented
@yogananth-subramanian @tonyskapunk @betoredhat ptal

2021-05-20 15:19 UTC, tonyskapunk requested changes

2021-05-21 02:54 UTC, krsacme commented on bundle/manifests/testpmd-operator.clusterserviceversion.yaml
> +                image: quay.io/rh-nfv-int/testpmd-operator@sha256:a725658acee30dd0d3782a2f4efee9cb949d10cf99dfd56250a8b7be34330bc7
Refer to the `bundle.Docker` file. It copies the manifests folders to the bundle container image. This modification is required as there are the files which will be available as part of the bundle, If sha mismatches, then it is easy to refer the the sha from the repo.

2021-05-21 02:57 UTC, krsacme commented on Makefile
> +docker-push-with-bundle:
`docker-push` is the default target which comes while creating the Makefile (and the operator) using the `operator-sdk` cli. I wanted to change the name as I don't want `make docker-push` to be available as it is the general operator build operation flow. I wanted to change the name to something else so that it is understood. Added `with-bundle` to signify that it has to be invoked with bundle.

2021-05-21 22:29 UTC, tonyskapunk commented on Makefile
> +all: docker-build bundle bundle-build
We can do one more thing here, and that is:

```suggestion
all: docker-build bundle-build
```

Since `bundle` is now a dependency of `bundle-build` a flow has been exemplified down below.

2021-05-21 22:29 UTC, tonyskapunk commented on Makefile
> +docker-push-with-bundle:
I understand what you're saying. I guess it doesn't hurt having one name or the other, because with the last change that particular target is not part of the default one (all) directly.

To reflect the old and new default target (`all`) in a flow:

old:  `docker-build` -> ` docker-push`
new: `docker-build` ->  ( `kustomize` -> `docker-push-with-bundle` ) -> `bundle` -> (`bundle`) -> `bundle-build`

_Here the parenthesis indicate that the grouped targets are dependencies of the target after them._

At the end the main difference is to do `kustomize` prior `docker-push-with-bundle` but that only installs kustomize binary, it really does not act on the docker-build.

One thing we could be done to simplify a bit the default `all` target and that is to use just `bundle-build` as that has a new dependency target that is `bundle`.

2021-05-21 22:29 UTC, tonyskapunk commented on bundle/manifests/testpmd-operator.clusterserviceversion.yaml
> +                image: quay.io/rh-nfv-int/testpmd-operator@sha256:a725658acee30dd0d3782a2f4efee9cb949d10cf99dfd56250a8b7be34330bc7
I see your point, and I can see how having a sha2 *in the repo* would be useful. The caveat I see is that we will need to update that manually on every release, it defeats the purpose of having the replacement in the `bundle` target when we do an inspect and replacement of the sha2.

@betoredhat and I were talking about this and we think is more clear to use a tag in the code as we would know what  version was used for an image and let the build process "translate" that to the sha2 and push the bundle automatically.  (see #7) besides the operator *and* the bundle will be built at the same time, if we do that automatically then we guarantee that the sha2 used in the bundle image belongs to the operator image created a step before.

Let me know what do you think about this, we created a PoC for the build process in my repo:

This is the GH A that builds the operator and the bundle and pushes it to my personal space in quay

- [build operator and bundle on tag](https://github.com/tonyskapunk/testpmd-operator/actions/runs/865309946)
- [operator image](https://quay.io/repository/tonyskapunk/testpmd-operator?tag=latest&tab=tags)
- [operator-bundle image](https://quay.io/repository/tonyskapunk/testpmd-operator-bundle?tag=latest&tab=tags)

2021-05-24 03:59 UTC, krsacme commented on bundle/manifests/testpmd-operator.clusterserviceversion.yaml
> +                image: quay.io/rh-nfv-int/testpmd-operator@sha256:a725658acee30dd0d3782a2f4efee9cb949d10cf99dfd56250a8b7be34330bc7
I will stick with the sha instead of versions in the code to replicate what is being installed as part of the CSV for reference. The version is always available in the make file.

2021-05-24 04:18 UTC, krsacme commented on bundle/manifests/testpmd-operator.clusterserviceversion.yaml
> +                image: quay.io/rh-nfv-int/testpmd-operator@sha256:a725658acee30dd0d3782a2f4efee9cb949d10cf99dfd56250a8b7be34330bc7
This approach makes the development complicated. I usually follow updating the make file to new version so that I can push the image ans work on the same repositories, Once it is stable I will publish the new version. Using this approach complicates the flow, now I have to rely on using own org name instead of rh-nfv-int for images. 

We can keep the tags and trigger build based on it. But for some time, can we keep the version as it is (manually modifiable)? We can add a check if tag name and version in make file mistakes, trigger a failure. It only keeps the development flow easier, maybe after few months, we can align the builds with tag.

2021-05-24 21:12 UTC, tonyskapunk commented on bundle/manifests/testpmd-operator.clusterserviceversion.yaml
> +                image: quay.io/rh-nfv-int/testpmd-operator@sha256:a725658acee30dd0d3782a2f4efee9cb949d10cf99dfd56250a8b7be34330bc7
Sounds good, I've added back the VERSION as it used to. I'm keeping the tag as the way to trigger the build of the images.

2021-05-24 21:13 UTC, tonyskapunk approved these changes
LGTM

2021-05-25 03:13 UTC, merged