Using sha and bumping ansible operator version
rh-nfv-int/testpmd-operator pull request #8
Opened 2021-05-24 20:54 UTC by betoredhat

- In order to make the operator compatible with disconnected mode, moving to SHA references in all related images 
- Adding related images to CSV
- The ansible-operator image has a new release available, the image is based on UBI and there is no metadata available in the packages about security updates. "yum -y update-minimal --security --sec-severity=Important --sec-severity=Critical" only works in RHEL, so it is needed to update all the packages. Certification is failing because no updates are been applied.

2021-05-24 21:26 UTC, tonyskapunk requested changes

2021-05-24 21:26 UTC, tonyskapunk commented on roles/testpmd/defaults/main.yml
> +image_testpmd: registry.redhat.io/openshift4/dpdk-base-rhel8@sha256:7a146c795271a45804209dcf3af4792498117d638c2eb4cfd69fe4cbf61d81eb
```suggestion
image_testpmd: registry.redhat.io/openshift4/dpdk-base-rhel8@sha256:7a146c795271a45804209dcf3af4792498117d638c2eb4cfd69fe4cbf61d81eb #v4.6
￼```

2021-05-24 21:26 UTC, tonyskapunk commented on roles/testpmd/defaults/main.yml
>  mac_workaround_enable: false
The line below this one won't be necessary any longer: `mac_workaround_version`

2021-05-24 21:26 UTC, tonyskapunk commented on roles/testpmd/tasks/main.yml
> +    mac_workaround_image: quay.io/rh-nfv-int/testpmd-container-app-mac@sha256:edc9bb4724d792d415df492aea1768d4127f7fe412d99e0bee8918a8008fcbce # v0.2.0
I think this one should be in `defaults/main.yml` instead, what do you think?

2021-05-24 21:26 UTC, tonyskapunk commented on roles/testpmd/defaults/main.yml
>  org: rh-nfv-int
I think these ones won't be needed any longer.  If we switch to use SHA2 everywhere then the only way to override will be directly with the name of the image.

2021-05-24 21:35 UTC, betoredhat commented on roles/testpmd/defaults/main.yml
>  mac_workaround_enable: false
It is needed in templates/daemonset.yml as value for an environment variable for the Daemonset

2021-05-24 21:51 UTC, betoredhat commented on roles/testpmd/tasks/main.yml
> +    mac_workaround_image: quay.io/rh-nfv-int/testpmd-container-app-mac@sha256:edc9bb4724d792d415df492aea1768d4127f7fe412d99e0bee8918a8008fcbce # v0.2.0
yeah, I moved the line.

2021-05-25 03:25 UTC, krsacme requested changes

2021-05-25 03:25 UTC, krsacme commented on bundle/manifests/testpmd-operator.clusterserviceversion.yaml
> +  relatedImages:
There should be an automated way to generate it instead of manually editing the files.

2021-05-25 03:25 UTC, krsacme commented on roles/testpmd/defaults/main.yml
>  mac_workaround_enable: false
It is needed till OCP 4.5 is supported.

2021-05-25 03:25 UTC, krsacme commented on roles/testpmd/defaults/main.yml
> +image_testpmd: registry.redhat.io/openshift4/dpdk-base-rhel8@sha256:7a146c795271a45804209dcf3af4792498117d638c2eb4cfd69fe4cbf61d81eb # v4.6
This parameter is overridable from ansible roles when TestPMD CR is created. sha can be updated there too.

2021-05-25 17:30 UTC, tonyskapunk commented on roles/testpmd/defaults/main.yml
> +image_testpmd: registry.redhat.io/openshift4/dpdk-base-rhel8@sha256:7a146c795271a45804209dcf3af4792498117d638c2eb4cfd69fe4cbf61d81eb # v4.6
Agreed, but this is the `default` value and I think we want to guarantee that we are using SHA2 to support disconnected environments.

2021-05-25 17:38 UTC, tonyskapunk commented on roles/testpmd/defaults/main.yml
>  mac_workaround_enable: false
Sounds good, then it would be nice to add a comment above the var indicating that is required fro ocp-4.5 so we can easily remove it once it's EOL.

2021-05-26 18:14 UTC, betoredhat commented on bundle/manifests/testpmd-operator.clusterserviceversion.yaml
> +  relatedImages:
At this time there is no easy way to do it: operator-framework/operator-sdk#4884
We can think of a method to automate it once we have agreements about how we are going to list in all code references to images. The tool will need to process the code to locate SHAs/Tags, make the proper replacements and generate the CSV.

With this change, we can start moving on to the main goal to be able to create the bundle able to support a disconnected environment.

2021-06-01 21:41 UTC, closed without merging